version: 2

jobs:
  build:
    docker:
      - image: microsoft/dotnet:1.1-sdk
    working_directory: ~/build
    steps:
      - checkout
      - run: dotnet --info
      - run: dotnet restore
      - run: dotnet build -c Release
      - run:
          name: dotnet xunit Freya.Core
          command: |
            mkdir -p /tmp/test-results/Freya.Core.Tests
            cd tests/Freya.Core.Tests
            dotnet xunit -xml /tmp/test-results/Freya.Core.Tests/TestResults.xml -configuration Release
      - run:
          name: dotnet xunit Freya.Core.Hopac
          command: |
            mkdir -p /tmp/test-results/Freya.Core.Hopac.Tests
            cd tests/Freya.Core.Hopac.Tests
            dotnet xunit -xml /tmp/test-results/Freya.Core.Hopac.Tests/TestResults.xml -configuration Release
      - store_test_results:
          path: /tmp/test-results
      - run: dotnet pack -c Release --include-source --include-symbols
      - store_artifacts:
          path: ~/build/src/Freya.Core/bin/Release
          destination: Freya.Core
      - store_artifacts:
          path: ~/build/src/Freya.Core.Hopac/bin/Release
          destination: Freya.Core.Hopac
