version: 2

jobs:
  build:
    docker:
      - image: microsoft/dotnet:1.1-sdk
    working_directory: ~/build
    steps:
      - checkout
      - run: dotnet --info
      - run: dotnet restore
      - run: dotnet build -c Release
      - run: cd tests/Freya.Core.Tests && dotnet xunit -xml $CIRCLE_TEST_REPORTS/Freya.Core.Tests -configuration Release
      - run: cd tests/Freya.Core.Hopac.Tests && dotnet xunit -xml $CIRCLE_TEST_REPORTS/Freya.Core.Hopac.Tests -configuration Release
      - run: dotnet pack -c Release --include-source --include-symbols
      - store_artifacts:
          path: ~/build/src/Freya.Core/bin/Release
          destination: Freya.Core
      - store_artifacts:
          path: ~/build/src/Freya.Core.Hopac/bin/Release
          destination: Freya.Core.Hopac
